### ISSUE TITLE
 FaceDetection demo Program exit without any error

### ISSUE THREAD

**Issue by tabs** [emgucv/emgucv#139]
i installed emgv with emgu by this way:
Install-Package EMGU.CV-CUDA -Version 3.4.1.2980

demo program exit and no error
while run into example project FaceDetection DetectFace.cs 
line 77
`               //Read the HaarCascade objects
               using (CascadeClassifier face = new CascadeClassifier(faceFileName))`
and i write like this:
`          IImage image;

         //Read the files as an 8-bit Bgr image  

         image = new UMat("lena.jpg", ImreadModes.Color); //UMat version
         //image = new Mat("lena.jpg", ImreadModes.Color); //CPU version
         GpuMat gpuimage = new GpuMat(); //GPU version
          gpuimage.Upload(image);
         long detectionTime;
         List<Rectangle> faces = new List<Rectangle>();
         List<Rectangle> eyes = new List<Rectangle>();
         DetectFace.Detect(
           gpuimage, "haarcascade_frontalface_default.xml", "haarcascade_eye.xml", 
           faces, eyes,
           out detectionTime);`

Program exit without any error

**Comment by tabs** [comment]
OK ,i solved this problem see 
[https://github.com/emgucv/opencv/tree/master/data/haarcascades_cuda](url)

**Comment by GaikwadPratik** [comment]
@emgucv , @tabs I am still getting error at https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/FaceDetection/Program.cs#L47 

`Emgu.CV.Util.CvException: OpenCV: icvXMLParse
   at VideoProcessing.ImageFaceRecog.Detect(IInputArray image, String faceFileName, String eyeFileName, List`1 faces, List`1 eyes, Int64& detectionTime) in C:\Users\pratik\Desktop\VideoProcessing\VideoProcessing\ImageFaceRecog.cs:line 78
   at VideoProcessing.Form1.btnImageCompare_Click(Object sender, EventArgs e) in C:\Users\pratik\Desktop\VideoProcessing\VideoProcessing\Form1.cs:line 104
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
   at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at VideoProcessing.Program.Main() in C:\Users\pratik\Desktop\VideoProcessing\VideoProcessing\Program.cs:line 19`


![image](https://user-images.githubusercontent.com/5595263/54482726-8808af00-481e-11e9-8947-84c6ebd6cfee.png)

The code is cloned from https://github.com/emgucv/emgucv/blob/master/Emgu.CV.Example/FaceDetection and I have installed emgu.cv using nugets.

![image](https://user-images.githubusercontent.com/5595263/54482759-f188bd80-481e-11e9-8824-a5756591c7b9.png)

 I tried xmls from https://github.com/emgucv/opencv/tree/5fc3987e9dc059443346cabcb22ce462717e8561/data/haarcascades_cuda,  https://github.com/emgucv/opencv/tree/5fc3987e9dc059443346cabcb22ce462717e8561/data/haarcascades

Awaiting for your response

**Comment by emgucv** [comment]
Two separate problems here:

1. **Original issue (silent exit)** — solved by the reporter: the CUDA `CascadeClassifier` requires cascade files from the `haarcascades_cuda` folder, not the regular `haarcascades` folder.

2. **`icvXMLParse` error (second commenter)** — this means the cascade XML file format is incompatible with the parser. Common causes:
   - Using a cascade file from a mismatched source (e.g. an old-format or third-party XML)
   - Pointing to the wrong file path (the classifier silently loads an unrecognised file)
   
   Use the cascade files that ship with OpenCV (`haarcascade_frontalface_default.xml` etc.) from the same version of OpenCV that Emgu CV was built against. The file can be found in the `data/haarcascades/` directory of the OpenCV source or in the Emgu CV example project's data folder.

Closing now.
