### ISSUE TITLE
TrackerKCF not working on Mac

### ISSUE THREAD

**Issue by ispysoftware** [emgucv/emgucv#314]
Crashes at Emgu.CV.ContribInvoke.cveTrackerKCFCreate

[ WARN:2] global /Users/canming/bb/cv_osx_x86_64/build/opencv/modules/core/src/utils/filesystem.cpp (478) getCacheDirectory Using world accessible cache directory. This may be not secure: /tmp/
Unhandled exception. Emgu.CV.Util.CvException: OpenCV: could not open directory: /tmp/opencv
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.ContribInvoke.cveTrackerKCFCreate(Single detectThresh, Single sigma, Single lambda, Single interpFactor, Single outputSigmaFactor, Single pcaLearningRate, Boolean resize, Boolean splitCoeff, Boolean wrapKernel, Boolean compressFeature, Int32 maxPatchSize, Int32 compressedSize, Mode descPca, Mode descNpca, IntPtr& tracker, IntPtr& sharedPtr)
   at Emgu.CV.Tracking.TrackerKCF..ctor(Single detectThresh, Single sigma, Single lambda, Single interpFactor, Single outputSigmaFactor, Single pcaLearningRate, Boolean resize, Boolean splitCoeff, Boolean wrapKernel, Boolean compressFeature, Int32 maxPatchSize, Int32 compressedSize, Mode descPca, Mode descNpca)
   at CoreLogic.Analyzers.TrackedObject..ctor(Int32 id, Mat frame, Rectangle rect)
   at CoreLogic.Analyzers.TrackerBase.Process(Mat f)
   at CoreLogic.Analyzers.MotionTracking.Process(Mat f)
   at CoreLogic.Objects.Camera.VideoSourceNewFrame(Object sender, NewFrameEventArgs e)
Fatal error. Internal CLR error. (0x80131506)
   at Emgu.CV.ContribInvoke.cveTrackerKCFCreate(Single, Single, Single, Single, Single, Single, Boolean, Boolean, Boolean, Boolean, Int32, Int32, Mode, Mode, IntPtr ByRef, IntPtr ByRef)
   at Emgu.CV.ContribInvoke.cveTrackerKCFCreate(Single, Single, Single, Single, Single, Single, Boolean, Boolean, Boolean, Boolean, Int32, Int32, Mode, Mode, IntPtr ByRef, IntPtr ByRef)
   at Emgu.CV.Tracking.TrackerKCF..ctor(Single, Single, Single, Single, Single, Single, Boolean, Boolean, Boolean, Boolean, Int32, Int32, Mode, Mode)
   at CoreLogic.Analyzers.TrackedObject..ctor(Int32, Emgu.CV.Mat, System.Drawing.Rectangle)
   at CoreLogic.Analyzers.TrackerBase.Process(Emgu.CV.Mat)
   at CoreLogic.Analyzers.MotionTracking.Process(Emgu.CV.Mat)
   at CoreLogic.Objects.Camera.VideoSourceNewFrame(System.Object, CoreLogic.Sources.NewFrameEventArgs)
   at CoreLogic.Sources.Combined.MediaStream.ReadFrames()
   at System.Threading.ThreadHelper.ThreadStart_Context(System.Object)
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by ispysoftware** [comment]
manually creating an opencv directory in /tmp/ resolves it

**Comment by ispysoftware** [comment]
@canmingh this is causing issues - any idea why opencv isn't creating the cache directory itself?

**Comment by emgucv** [comment]
Looks like "/tmp" is a pre-existing (system created) folder on Mac OS on Big Sur 11.4.

**Comment by emgucv** [comment]
This is an OpenCV-level behavior — it attempts to open /tmp/opencv as a cache directory without creating it. The workaround found at the time was to create the directory manually. This is no longer reproducible with current versions of OpenCV. Closing now.
