### ISSUE TITLE
libdl.so missing

### ISSUE THREAD

**Issue by ispysoftware** [emgucv/emgucv#315]
I've got this working on ubuntu and am now testing on linux mint. When my app starts up it's crashing with an error saying unable to load shared library 'dl' which from the source code I guess is libdl.so. This file does exist on my ubuntu instance but not on linux mint.

Are there any prerequisites I need to install on linux to get this working with a pre-built binary? Is there any way to statically link these dependencies into the libcvextern.so library so it's portable?

**Comment by emgucv** [comment]
You need to build the ".so" files on Linux Mint. If you try to use the ".so" files built from ubuntu it will quite likely failed. Each Linux distribution are different, they may have different package manager and the native dependencies can be quite different.  

They could comes with different versions of the most basic libraries such as libc.so & libm.so 

For Linux distribution, you will need to compile for each major linux distribution. We have build instructions for Ubuntu and Raspbian but we have not tried our build on Linux Mint. We do not support Linux Mint at this moment.

**Comment by ispysoftware** [comment]
It seems the main stumbling block to getting it working is libgtk - I don't need that personally, or a whole heap of other stuff like tesseract or ffmpeg. I've tried adding -DBUILD_opencv_text:BOOL=FALSE to cmake_configure.sh which should disable tesseract but every time it runs the build it builds tesseract anyway and fails when it requires libgtk. Do you have any idea how to do a completely minimal build with minimal dependencies (and therefore maximum portability)?

**Comment by ispysoftware** [comment]
it's weird - my project is using a lot of .so libraries but on every linux distro i've tried opencv is the only one that needs to be built specifically for that OS. Every other .so library is loading fine across the various linux platforms - is there anything specific that can be taken out of the build to make it more portable?

**Comment by emgucv** [comment]
It your other projects are self contained. It is easier to make it potable between Linux platforms. Open CV depends on quite a few other libraries to read / write files, access camera and UI components. 
The following opencv pages list packages you will need to install before you build opencv, which open cv will also depends on:
https://docs.opencv.org/master/d7/d9f/tutorial_linux_install.html

If you want to re-configure the project to eliminate some of the dependencies. I have added instructions for re-configuring the project:
http://www.emgu.com/wiki/index.php/Download_And_Installation#Ubuntu

Once you run the configuration script, the output will show you part of the dependencies. Which you will need to make sure it is on the other platforms you are using. If you disabled those modules it should be labelled "NO".

```
...
--  GUI: 
--     GTK+:                        YES (ver 3.22.30)
--       GThread :                  YES (ver 2.56.4)
--       GtkGlExt:                  NO
--     VTK support:                 YES (ver 8.2.0)
-- 
--   Media I/O: 
--     ZLib:                        /usr/lib/x86_64-linux-gnu/libz.so (ver 1.2.11)
--     JPEG:                        /usr/lib/x86_64-linux-gnu/libjpeg.so (ver 80)
--     WEBP:                        build (ver encoder: 0x020f)
--     PNG:                         /usr/lib/x86_64-linux-gnu/libpng.so (ver 1.6.34)
--     TIFF:                        /usr/lib/x86_64-linux-gnu/libtiff.so (ver 42 / 4.0.9)
--     JPEG 2000:                   build Jasper (ver 1.900.1)
--     OpenEXR:                     /usr/lib/x86_64-linux-gnu/libImath.so /usr/lib/x86_64-linux-gnu/libIlmImf.so /usr/lib/x86_64-linux-gnu/libIex.so /usr/lib/x86_64-linux-gnu/libHalf.so /usr/lib/x86_64-linux-gnu/libIlmThread.so (ver 2_2)
--     HDR:                         YES
--     SUNRASTER:                   YES
--     PXM:                         YES
--     PFM:                         YES
-- 
--   Video I/O:
--     DC1394:                      YES (2.2.5)
--     FFMPEG:                      YES
--       avcodec:                   YES (57.107.100)
--       avformat:                  YES (57.83.100)
--       avutil:                    YES (55.78.100)
--       swscale:                   YES (4.8.100)
--       avresample:                NO
--     GStreamer:                   NO
--     v4l/v4l2:                    YES (linux/videodev2.h)
-- 
--   Parallel framework:            TBB (ver 2017.0 interface 9107)
-- 
--   Trace:                         YES (with Intel ITT)
-- 
...
```

**Comment by ispysoftware** [comment]
awesome - thank you. By the way you have a typo - EMGU_CV_WITH_TEESERACT

**Comment by ispysoftware** [comment]
I turned basically everything off and built it but it failed here:
(everything tesseract related is disabled)

[ 65%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/vector_Rect.cpp.o
[ 65%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/vector_TesseractResult.cpp.o
In file included from /home/sean/Desktop/emgucv/Emgu.CV.Extern/vector_TesseractResult.cpp:12:0:
/home/sean/Desktop/emgucv/Emgu.CV.Extern/vector_TesseractResult.h:19:10: fatal error: tesseract_c.h: No such file or directory
 #include "tesseract_c.h"

**Comment by emgucv** [comment]
Fixed in this commit: 0a36053f928e720085a21854deb5e9e09b6b65ca

Please do a pull and re-run make.

Typo in EMGU_CV_WITH_TEESERACT also fixed. Thanks for pointing out.

**Comment by ispysoftware** [comment]
i've got videostab disabled - also flann is having a similar issue

[ 62%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/optflow/rlof_opticalflow_parameter_property.cpp.o
In file included from /home/sean/Desktop/emgucv/Emgu.CV.Extern/videostab/videostab_c.cpp:8:0:
/home/sean/Desktop/emgucv/Emgu.CV.Extern/videostab/videostab_c.h:80:39: error: ‘cv::videostab’ has not been declared
 class CaptureFrameSource : public cv::videostab::IFrameSource

**Comment by ispysoftware** [comment]
videostab and ximgproc are both off..

[ 88%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/face/facemarkaam_params_property.cpp.o
[ 88%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/face/facemarklbf_params_property.cpp.o
[ 89%] Building CXX object Emgu.CV.Extern/CMakeFiles/cvextern.dir/ximgproc/ximgproc_c.cpp.o
In file included from /home/sean/Desktop/emgucv/Emgu.CV.Extern/videostab/videostab_c.cpp:8:0:
/home/sean/Desktop/emgucv/Emgu.CV.Extern/videostab/videostab_c.h:80:39: error: ‘cv::videostab’ has not been declared
 class CaptureFrameSource : public cv::videostab::IFrameSource
                                       ^~~~~~~~~
/home/sean/Desktop/emgucv/Emgu.CV.Extern/videostab/videostab_c.h:80:50: error: expected ‘{’ before ‘IFrameSource’
 class CaptureFrameSource : public cv::videostab::IFrameSource
                                                  ^~~~~~~~~~~~

**Comment by ispysoftware** [comment]
looks like you have to also remove them from cmakelists.txt

SET (OPENCV_MODULE_NAME_CANDIDATES
  core hal imgproc video flann ml imgcodecs videoio highgui objdetect features2d calib3d
  cudaarithm cudawarping cudafilters cudaimgproc cudalegacy cudaoptflow 
  cudastereo cudabgsegm cudafeatures2d cudacodec cudaobjdetect
  photo superres  
  videostab shape
  cudev  
  face ximgproc xobjdetect xfeatures2d xphoto bgsegm optflow
  stitching latentsvm plot
  dnn dnn_objdetect dnn_superres aruco fuzzy viz bioinspired text tracking
  dpm
  saliency
  dnn_modern
  img_hash
  phase_unwrapping
  freetype
  hfs
  quality
  stereo
  surface_matching
  alphamat
  )

**Comment by ispysoftware** [comment]
i got it building by removing the various modules from cmakelists.txt. It builds OK now but when i try and call it from the project I get:

Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
 ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.CheckLibraryLoaded()
   at Emgu.CV.MatInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.MatInvoke.cveMatCreate()
   at Emgu.CV.Mat..ctor()

- ldd libcvextern.so doesn't show anything missing - when I call make do i need to pass it any other flags like fPIC? I noticed that fPIC isn't set in cmake_c_flags  or cmake_cxx_flags but adding it there didn't seem to make a difference
