### ISSUE TITLE
CudaCascadeClassifier throws exception

### ISSUE THREAD

**Issue by TheSwerik** [emgucv/emgucv#328]
CudaInvoke.HasCuda is true, but i still get this error when Initializing CudaCascadeClassifier:
```
Unhandled exception. System.TypeInitializationException: The type initializer for 'RedEye.Detector' threw an exception.
 ---> Emgu.CV.Util.CvException: OpenCV: The called functionality is disabled for current build or platform
   at Emgu.CV.CvInvoke.CvErrorHandler(Int32 status, IntPtr funcName, IntPtr errMsg, IntPtr fileName, Int32 line, IntPtr userData)
   at Emgu.CV.Cuda.CudaInvoke.cudaCascadeClassifierCreate(IntPtr filename, IntPtr& sharedPtr)
   at Emgu.CV.Cuda.CudaCascadeClassifier..ctor(String fileName)
```

**Comment by TheSwerik** [comment]
I'm on C# .Net core 3.1 with Emgu.cv.runtime.windows.cuda 4.2.0.3662 via NuGet

**Comment by emgucv** [comment]
Duplicate of #257

We will be removing CudaCascadeClassifier. It has been disabled in Open CV.

**Comment by TheSwerik** [comment]
But what do I need to use for Cuda then?

**Comment by nosajthenitram** [comment]
FYI - I'm trying to get this pulled back into OpenCV 4.x. 

You can follow here for more: https://github.com/opencv/opencv_contrib/issues/2048

I've got my work up on a branch, and going to test it against emguCV. Hopefully they don't remove it too quickly.

**Comment by nosajthenitram** [comment]
I've verified that the branch posted above does work with emguCV and cuda cascade classifiers are working. I'll continue to work with the OpenCV guys until the PR is integrated into 4.30, until then, the branch is there and working for anyone adventurous enough to compile emguCV.

**Comment by nosajthenitram** [comment]
@emgucv Cuda cascade classifiers are back into OpenCV4.3, please do not remove the support from emgucv.

**Comment by emgucv** [comment]
The pull request https://github.com/opencv/opencv_contrib/pull/2554 was merged (June 11, 2020) after the official Open CV 4.3 release (Apr 3rd, 2020), it is not in the official v4.3 release. It should be in the next Open CV release, where we will re-enable CudaCascadeClassifier.

**Comment by emgucv** [comment]
This commit b78de26c74f9ed0ecc40c59fbc0b51adb021479f re-enabled CudaCascadeClassifier.

**Comment by nosajthenitram** [comment]
Impressive 6 years to close this issue!
