### ISSUE TITLE
Unable to load DLL 'cvextern' or one of its dependencies

### ISSUE THREAD

**Issue by janracz** [emgucv/emgucv#361]
I'm getting this kind of error
```
System.TypeInitializationException
Message : The type initializer for 'Emgu.CV.MatInvoke' threw an exception.
StackTrace :    at Emgu.CV.MatInvoke.cveMatCreate()
   at Emgu.CV.Mat..ctor(String fileName, ImreadModes loadType)
   at LightingPreprocessor.GASVDF..ctor() in C:\Users\Jasiek\Source\Repos\Stadion\Stadion\Stadion\LightingPreprocessor\GASVDF.cs:line 26
System.TypeInitializationException
Message : The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
StackTrace :    at Emgu.CV.CvInvoke.CheckLibraryLoaded()
   at Emgu.CV.MatInvoke..cctor()
System.DllNotFoundException
Message : Unable to load DLL 'cvextern' or one of its dependencies: Nie można odnaleźć określonego modułu. (0x8007007E)
StackTrace :    at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
```
I'm working on Visual Studio 2019. I have Emgu.Cv and Emgu.Cv.runtime.windows from NuGet.
I was troubleshooting this by instaling Windows Media Feature Pack, instaling Visual C++ Redistributable for Visual Studio 2019, I created PATH for this DLL's, copied DLL's to both x86 and x64 folders, uninstalling and reinstalling packages again and making a new solution. None of which worked. Is there anything else which I can try so I can make it work?

The error ocures at this line:
`var image = new Mat(pPath, ImreadModes.Color);`

**Comment by neonleo** [comment]
I have this issue yesterday, I change my project target platform from AnyCPU to x64 and build success, have a try.
In general, if your project reference the dll by Nuget, you don't have to copy CvExtern to bin or build folder manually.

**Comment by Shivanand137** [comment]
Yes! @neonleo's update 2 worked for me. I am using EmguCV 4.5.1 for image processing and came across this same error. So apart from the Emgu.CV package, I installed the runtime package as recommended and the error went away.

![image](https://user-images.githubusercontent.com/3062052/121512823-c2feea80-ca07-11eb-8f4f-2cf739c12f55.png)

Development environment - Windows 10 - 64 bit processor.
IDE - Visual Studio 2019

**Comment by emgucv** [comment]
If you are targeting .Net Framework, you need to target either "x64" or "x86". If you are targeting ".Net Core" or ".Net 5", you can target "AnyCPU". Detail can be found here:
https://www.emgu.com/wiki/index.php/Download_And_Installation#Targeting_.Net_Framework

**Comment by liakat89** [comment]
> I have this issue yesterday, I change my project's target platform from AnyCPU to x64 and build success, please have a try.
> In general, if your project reference the dll by Nuget, you don't have to copy CvExtern to bin or build folder manually.
> 
> Update2: Anyone occur this error, may install Emgu.CV.runtime.windows package from NUGET, this will fix the dll missing error.

This was the solution for me

**Comment by mariarzv** [comment]
I have the runtime package installed and my project's target platform is x64 but that doesn't resolve the issue. The NuGet packages version is the same - 4.6.0.5131

**Comment by blauertee** [comment]
> I have the runtime package installed and my project's target platform is x64 but that doesn't resolve the issue. The NuGet packages version is the same - 4.6.0.5131

Have you had any success yet? @mariarzv

**Comment by blauertee** [comment]
Something that makes me curious I added `CopyLocalLockFileAssemblies` to my .csproj. Which results in copying all the needed DLLs to the output directory. Emgu.CV.dll is copied. But cvextern.dll is not even though it is refernced by Emgu.CV.runtime.mini.windows. How can that be?

**Comment by emgucv** [comment]
There are two different kinds of binaries:
Emgu.CV.dll (part of Emgu.CV nuget package) is the managed dll and will be copied to the same folder of the executable.
cvextern.dll (part of the Emgu.CV.runtime.* nuget package) is the C++ Open CV dll. They (multiple-versions) are deployed by the nuget package to "runtime" subfolder, where the managed dll will pick the correct one depends on the system it is running on. The Emgu.CV.runtime.windows / Emgu.CV.runtime.mini.windows nuget package contains the binary for 3 different architectures: x86, x86_64 & arm.
