### ISSUE TITLE
Unhandled Exception: System.AccessViolationException in Release mode

### ISSUE THREAD

**Issue by LoriBru** [emgucv/emgucv#541]
Hi, I am facing an Unhandled Exception: System.AccessViolationException while using Emgu.
More specifically when calling Emgu.CV.Features2D.Feature2D.DetectAndCompute().

My code is doing this:

```
internal (VectorOfKeyPoint kp, Mat des) ComputeDescriptors(Image<Gray, byte> imageCV)
{
    var featureDetector = new Emgu.CV.Features2D.SIFT();
    var kp = new VectorOfKeyPoint();
    var des = new Mat();
    featureDetector.DetectAndCompute(imageCV, null, kp, des, false);
    return (kp, des);
}
```

And I get the following exception:
```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Emgu.CV.Features2D.Features2DInvoke.CvFeature2DDetectAndCompute(IntPtr feature2D, IntPtr image, IntPtr mask, IntPtr keypoints, IntPtr descriptors, Boolean useProvidedKeyPoints)
   at Emgu.CV.Features2D.Feature2D.DetectAndCompute(IInputArray image, IInputArray mask, VectorOfKeyPoint keyPoints, IOutputArray descriptors, Boolean useProvidedKeyPoints)
```

I am using a WPF application with x64 target only, .NET Framework 4.8 and the latest Emgu and Runtime packages available.
The thing is that this happens only in Release mode, while in Debug mode I have no issues.

Could this be related to Emgu?
Thank you for any very welcome suggestion about how to investigate/solve the issue.

**Comment by emgucv** [comment]
Can you also include the image that can be uesd to reproduce the issue? We cannot reproduce it with the following image converted to grayscale:

https://github.com/emgucv/emgucv/blob/4.5.3/Emgu.CV.Example/XamarinForms/Core/box.png

**Comment by jzylkin** [comment]
Hi, it is suspicious that the error happens when you enable optimization. I believe what must be happening is that either your compiler is deciding not to allocate some of these objects (because they are not used by managed code) or the garbage collector is disposing them prematurely, for the same reason.  You should be able to resolve this by using GC.Keepalive() method or else using each variable within a "using" block so that its lifetime is defined deterministically.

**Comment by emgucv** [comment]
The diagnosis in the second comment is correct. When the JIT optimizer is enabled it can determine that `featureDetector`, `kp`, and `des` are no longer reachable from managed code before `DetectAndCompute` returns, so the GC is free to finalize and release their unmanaged memory while the native call is still running. The `AccessViolationException` is the result of the native code reading freed memory.

The fix is to keep a live managed reference to each object until the call completes:

```csharp
featureDetector.DetectAndCompute(imageCV, null, kp, des, false);
GC.KeepAlive(featureDetector);
GC.KeepAlive(kp);
GC.KeepAlive(des);
```

or wrap each in a `using` block, which gives the object a deterministic lifetime that the JIT cannot move past.

Note also that `Image<,>` is not available in Emgu CV 5 (it was based on IplImage, which was removed in OpenCV 5). The equivalent pattern using `Mat`:

```csharp
static Mat NetVipsToOpenCV(byte[] mem, int width, int height)
{
    var mat = new Mat(height, width, DepthType.Cv8U, 1);
    mat.GetSpan<byte>().Clear(); // zero if needed
    mem.AsSpan().CopyTo(mat.GetSpan<byte>());
    return mat;
}
```

With `Mat`, the pixel data is owned by the native side from the start, so there is no risk of the managed byte array being moved or collected out from under the native call.

Closing now.
