### ISSUE TITLE
[BUG] Running emgucv on linux docker doesn't work with a published project

### ISSUE THREAD

**Issue by Webreaper** [emgucv/emgucv#549]
**Describe the bug**
In my ongoing mission to try and successfully deploy a .Net 5.0 app that used EmguCV, I'm trying to run a published app. However, the app doesn't work if you use `dotnet publish` (and fails with the cvextern missing dependency per [the previous issue I raised](https://github.com/emgucv/emgucv/issues/544)). The project runs fine using `dotnet run`.

**OS / Platform:** Ubuntu 20.04 docker image. 
**.Net version:** .Net 5
**CPU Architecture:** x64
**Emgu CV package used:** Emgu.CV.runtime.ubuntu.20.04-x64 v4.5.1.4349

**To Reproduce**

I've attached a sample based on the one we were using earlier, but using a 'clean' image based on `ubuntu:20.04`. 

[EmguPublishSample.zip](https://github.com/emgucv/emgucv/files/6877265/EmguPublishSample.zip)

This prepares the docker image, and runs `dotnet publish`. If you build the container and then run the image

```
   docker run --name emgutest <imagename>
```

You'll see the output like this. The app is run 3 times:
1. Using `dotnet run` [**Succeeds**]
2. Using the binaries built by the dotnet build (in /emgu/bin/Release/net5.0/linux-x64/) [**FAILS**]
3. Using the binaries produced by the `dotnet publish` (in /emgu/bin/Release/net5.0/linux-x64/publish) [**FAILS**]

The output is as follows:

```
Dotnet Run:
/emgu/emgu.csproj : warning NU1602: Emgu.CV.runtime.ubuntu.20.04-x64 4.5.1.4349 does not provide an inclusive lower bound for dependency Emgu.CV (> 4.5.1 && < 4.5.2). An approximate best match of Emgu.CV 4.5.1.4349 was resolved.
/emgu/emgu.csproj : warning NU1602: Emgu.CV.runtime.ubuntu.20.04-x64 4.5.1.4349 does not provide an inclusive lower bound for dependency Emgu.CV (> 4.5.1 && < 4.5.2). An approximate best match of Emgu.CV 4.5.1.4349 was resolved.
Starting....
Initialising face detector....
Initialising grayscale image....
Detecting faces....
Processing 4 faces...
Found face: 273 33 59 59
Found face: 197 28 73 73
Found face: 184 136 103 103
Found face: 288 143 137 137
Processing complete.
Run Compiled:
Starting....
Exception: System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at EmguCVSample.Program.Main(String[] args) in /emgu/Program.cs:line 19
Run Published:
Starting....
Exception: System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'cvextern' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libcvextern: cannot open shared object file: No such file or directory
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at EmguCVSample.Program.Main(String[] args) in /emgu/Program.cs:line 19
```

**Expected behavior**
If my docker image has the dependencies installed correctly, then the project should work correctly from a built or published project, i.e., all three runs should succeed. Currently, this means I cannot deploy a build using emgu using a published app (which means reduced optimisations, and having to ship the entire runtime, which is a waste of space).

**Comment by Webreaper** [comment]
Seems the problem was highlighted here around 10 months ago: https://stackoverflow.com/questions/63791891/running-emgu-cv-on-linux

**Comment by emgucv** [comment]
This new demo first use "dotnet publish" to publish the app, then copy it to a different directory and run it. Works without any issues:
https://github.com/emgucv/emgucv/tree/a1e3171906427cb5a77e79e9c260ef50b485ba36/Emgu.CV.Example/Docker/Ubuntu

The docker file looks like this:
https://github.com/emgucv/emgucv/blob/a1e3171906427cb5a77e79e9c260ef50b485ba36/Emgu.CV.Example/Docker/Ubuntu/Dockerfile

**Comment by Webreaper** [comment]
Interesting. Is that with 4.5.2 or 4.5.3? It definitely doesn't work for me with publish unless I manually copy the lib.

**Comment by emgucv** [comment]
That's with 4.5.3. 

Also tested with 4.5.1 nuet package using the Programs.cs file from 4.5.1 release and work.

**Comment by Webreaper** [comment]
Weird. Not sure what to suggest - the issue with example I attached is 100% reproducible. 

It's not an issue for me for now, as I've got a step in my build to manually copy the .so, and that seems to work: 
https://github.com/Webreaper/Damselfly/blob/develop/scripts/makeserver.sh#L37

**Comment by emgucv** [comment]
The `dotnet publish` + Docker pattern has been working correctly for several major versions. The current working example is in the repo at [`Emgu.CV.Example/Docker/Ubuntu/Dockerfile`](https://github.com/emgucv/emgucv/blob/EMGUCV_5_0/Emgu.CV.Example/Docker/Ubuntu/Dockerfile) — it uses .NET 8 and `Emgu.CV.runtime.ubuntu-x64`, runs `dotnet publish -c Release`, and then executes the self-contained binary directly (`./emgu`). The native `libcvextern.so` is included in the publish output automatically.

Two things worth noting for anyone hitting this with older setups:
- Use `Emgu.CV.runtime.ubuntu-x64` (not the older `ubuntu.20.04-x64` package); .NET 8 RID resolution handles the rest.
- Run the published binary as a self-contained executable rather than via `dotnet <app>.dll` to avoid RID asset resolution issues at runtime.

Closing now.
