### ISSUE TITLE
Running Emgu in server IIS

### ISSUE THREAD

**Issue by joaobdc** [emgucv/emgucv#58]
Hi, I'm having some issues running the Emgu on my server. It runs fine locally, but when I try to use it in the server with an IIS it doesnt work.

Here is the error:
System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'cvextern': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)\r\n   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.cvCreateImageHeader(Size size, IplDepth depth, Int32 channels)
   at Emgu.CV.Image`2.AllocateData(Int32 rows, Int32 cols, Int32 numberOfChannels)
   at Emgu.CV.Image`2.set_Bitmap(Bitmap value)
   at VerifyID.Managers.ImageTreatmentsManager.ExtractDocumentFromImage(Bitmap bitmap)
   at VerifyID.VerifyWorker.ExecuteOCR(BigIdRequest request, BigIdEvent bigIdEvent)

I have the following dlls inside the x86 and x64:
concrt140.dll*  liblept172.dll*       msvcp140.dll*          vcruntime140.dll*
cvextern.dll*   libtesseract304.dll*  opencv_ffmpeg320.dll*

IIS version: 10.0

Could someone help ?

**Comment by joaobdc** [comment]
After copying the x64 dlls directly to the bin directory of the build the error changed to:

`System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)\r\n   at Emgu.CV.CvInvoke.RedirectError(CvErrorCallback errorHandler, IntPtr userdata, IntPtr prevUserdata)\r\n   at Emgu.CV.CvInvoke..cctor()\r\n   --- End of inner exception stack trace ---\r\n   at Emgu.CV.CvInvoke.cvCreateImageHeader(Size size, IplDepth depth, Int32 channels)\r\n   at Emgu.CV.Image`2.AllocateData(Int32 rows, Int32 cols, Int32 numberOfChannels)\r\n   at Emgu.CV.Image`2.set_Bitmap(Bitmap value)\r\n   at VerifyID.Managers.ImageTreatmentsManager.ExtractDocumentFromImage(Bitmap bitmap)\r\n   at VerifyID.VerifyWorker.ExecuteOCR(BigIdRequest request, BigIdEvent bigIdEvent)`

**Comment by jovargas** [comment]
Wich Windows Server version are you running? 
Had the same problem on WS 2012 R2, I then tested on WS 2016 Standard and it worked.
There is something about Microsoft Mainstream support for older versions that avoids EmguCV to work properly.

**Comment by bernd5** [comment]
- The default .net runtime is 32 Bit... (BadImageFormatException usually means a 32 bit app found / tried to load a 64 bit dll)

**Comment by vzhadeyev** [comment]
Try to copy both x86 and x64 folder and configure build for "Any CPU", so it will depend only on your IIS AppPool settings (if you have no any other dependences built for specific architecture).

**Comment by Sopheakmorm** [comment]
Hey @joaobdc , you need to enable UI Desktop experience for windows server because Microsoft never enabled that feature on Windows Server by default,
You can follow these above steps : 
[Enable Desktop Experience on Window Server ](https://www.google.com.kh/url?sa=i&rct=j&q=&esrc=s&source=images&cd=&ved=0ahUKEwitssPx6-rXAhUJR48KHRbFCh8QjBwIBA&url=https%3A%2F%2Fmsdnshared.blob.core.windows.net%2Fmedia%2FTNBlogsFS%2Fprod.evol.blogs.technet.com%2FCommunityServer.Blogs.Components.WeblogFiles%2F00%2F00%2F00%2F79%2F57%2Fmetablogapi%2F0207.5-1-2012-3-18-02-PM_34B5D1E6.png&psig=AOvVaw2JoB8wHqZhRpJLEm3l4UZP&ust=1512287445193117)


Hope this solution can help you :)

**Comment by Ralpharoo** [comment]
Thanks @Sopheakmorm. After hours of investigation our Windows 2012R2 server needed this Desktop Experience feature. After installing this, all working as expected :+1:

**Comment by Sopheakmorm** [comment]
Good job @Ralpharoo

**Comment by chamnan** [comment]
@Sopheakmorm you're awesome, saved my day.

**Comment by a-jahanshahlo** [comment]
@Sopheakmorm OMG this take several hours from me.
You are really awesome . 🥇

**Comment by Squiggle** [comment]
Thanks for the solution. This fixed it for us as well.

**emgucv team** - is this requirement documented anywhere?

**Comment by aanjunian** [comment]
Subhanallah, Alhamdulillah... Jazakallah khoir @Sopheakmorm Thanks a lot

**Comment by huytran123** [comment]
I have same issue when i publish website on IIS Server, are there any solutions  if i can not "Enable Desktop Experience on Window Server". Because i am using share hosting. My Services Provider do not allow "Enable Desktop Experience on Window Server".

Thanks All

**Comment by emgucv** [comment]
Two distinct problems, both solved by the community above:

1. **`DllNotFoundException: cvextern`** — the native DLLs were not on the DLL search path. For IIS, place them in the application's `bin` folder or set `PATH`. Current Emgu CV NuGet packages handle this automatically via `runtimes/<rid>/native/`.

2. **`BadImageFormatException`** — the IIS application pool was running as 32-bit but the DLLs placed in `bin` were x64. Solution: set the app pool to **No** on "Enable 32-bit Applications", or use the NuGet runtime packages which place both x86 and x64 binaries in the correct `runtimes/` subfolders.

3. **Windows Server — Desktop Experience** — some older versions of Emgu CV had transitive dependencies on GDI/graphics components that are not installed on Windows Server by default. Enabling the "Desktop Experience" feature installs them. In current Emgu CV (5.x), this dependency is reduced since `Image<,>` (which depended on GDI+) has been removed.

Closing now.
