### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by martienpoels-bank2loyalty** [emgucv/emgucv#651]
**Describe the bug**
If I try to apply a rotate operation on an image that has a format of <Rgb,int> or <Rgba,int>

No matter what I select for degrees the function crashes consistently:
```
   at Emgu.CV.CvInvoke.cveWarpAffine(IntPtr src, IntPtr dst, IntPtr mapMatrix, Size& dsize, Int32 flags, BorderType borderMode, MCvScalar& fillval)
   at Emgu.CV.CvInvoke.WarpAffine(IInputArray src, IOutputArray dst, IInputArray mapMatrix, Size dsize, Inter interMethod, Warp warpMethod, BorderType borderMode, MCvScalar borderValue)
   at Emgu.CV.Image`2.WarpAffine(Mat mapMatrix, Int32 width, Int32 height, Inter interpolationType, Warp warpType, BorderType borderMode, TColor backgroundColor)
   at Emgu.CV.Image`2.WarpAffine(Mat mapMatrix, Inter interpolationType, Warp warpType, BorderType borderMode, TColor backgroundColor)
   at Emgu.CV.Image`2.Rotate(Double angle, PointF center, Inter interpolationMethod, TColor background, Boolean crop)
   at Emgu.CV.Image`2.Rotate(Double angle, TColor background, Boolean crop)
   at TesseractTesting.FormMain.ButtonProcess_Click(Object sender, EventArgs e) in D:\GitHub\Test\TesseractTesting\TesseractTesting\FormMain.cs:line 104
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, WM msg, IntPtr wparam, IntPtr lparam)
   at Interop.User32.DispatchMessageW(MSG& msg)
   at System.Windows.Forms.Application.ComponentManager.Interop.Mso.IMsoComponentManager.FPushMessageLoop(UIntPtr dwComponentID, msoloop uReason, Void* pvLoopData)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(msoloop reason, ApplicationContext context)
   at System.Windows.Forms.Application.Run(Form mainForm)
   at TesseractTesting.Program.Main() in D:\GitHub\Test\TesseractTesting\TesseractTesting\Program.cs:line 20
```

** OS / Platform **
Windows

** .Net version **
 .Net Core 5

**CPU Architecture**
e.g. x86_64,  x86

** Emgu CV package used**
4.5.4.4788
Emgu.CV, 
Emgu.CV.Bitmap
Emgu.CB.runtime.windows

**To Reproduce**
var myImg = new Emgu.CV.Image<Rgb, int>("testimage.bmp");
var myRotaged = myImg.Rotate(10, new Rgb(), true);

**Expected behavior**
The rotation should be performed. It seems a very structural one because I tested it with all kind of images. But if I load the images
as greyscale it works perfect. But crashes consequently when trying to do this with Rgb or Rgba images.

**Comment by emgucv** [comment]
Probably because the kernal for rotating image of RGB/RGBA with depth of "int" is not implemented in Open CV. 

"int" is not a well supported image depth type in Open CV. Use Image<Rgb, byte> and it should rotate.

**Comment by martienpoels-bank2loyalty** [comment]
Have test it with <Rgb, byte> and I can confirm that did work. For my application greyscale does the job. But it just puzzled me why. All clear now.
