### ISSUE TITLE
Trying to load libopencv_videoio_ffmpeg454_64.so using default path.

### ISSUE THREAD

**Issue by gsargent70** [emgucv/emgucv#653]
I have been battling trying to get EMGUCV running in Ubuntu 21.10 for the past week.  It is being used by the UVTools application.  Here is what I have done.

- Installed dependencies
- Verified all dependencies met with ldd libcvextern.so
- Installed .NET 5 & 6
- Compiled a new libcvextern.so from scratch with no errors

When I run the program the errors are as follows

Unhandled exception. System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception.
 ---> System.DllNotFoundException: Unable to load shared library 'dl' or one of its dependencies. In order to help diagnose loading problems, consider setting the LD_DEBUG environment variable: libdl: cannot open shared object file: No such file or directory
   at Emgu.Util.Toolbox.Dlopen(String dllname, Int32 mode)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.Init()
   at UVtools.WPF.App.OnFrameworkInitializationCompleted() in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\App.axaml.cs:line 70
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__140_0(Object state)
   at Avalonia.Threading.AvaloniaSynchronizationContext.<>c__DisplayClass5_0.<Post>b__0() in /_/src/Avalonia.Base/Threading/AvaloniaSynchronizationContext.cs:line 33
   at Avalonia.Threading.JobRunner.Job.Avalonia.Threading.JobRunner.IJob.Run() in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 166
   at Avalonia.Threading.JobRunner.RunJobs(Nullable`1 priority) in /_/src/Avalonia.Base/Threading/JobRunner.cs:line 37
   at Avalonia.X11.X11PlatformThreading.CheckSignaled() in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 164
   at Avalonia.X11.X11PlatformThreading.RunLoop(CancellationToken cancellationToken) in /_/src/Avalonia.X11/X11PlatformThreading.cs:line 244
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken cancellationToken) in /_/src/Avalonia.Base/Threading/Dispatcher.cs:line 61
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[] args) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 126
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime[T](T builder, String[] args, ShutdownMode shutdownMode) in /_/src/Avalonia.Controls/ApplicationLifetimes/ClassicDesktopStyleApplicationLifetime.cs:line 175
   at UVtools.WPF.Program.Main(String[] args) in D:\Tiago\Dropbox\Programming\C#\UVtools\UVtools.WPF\Program.cs:line 47
./UVtools.sh: line 3: 142559 Aborted                 (core dumped) ./UVtools

In the Ubuntu sys log I get the following 

Trying to load libopencv_videoio_ffmpeg454_64.so using default path.

Any help would be greatly appreciated.

**Comment by emgucv** [comment]
Just updated the demo here to tested out Emgu.CV.runtime.ubuntu.20.04-x64 4.5.4.4788 release:

https://github.com/emgucv/emgucv/tree/master/Emgu.CV.Example/Docker/Ubuntu

Works without problems under a Ubuntu 20.04 docker image. No errors.

We have not tested on Ubuntu 21.10, we will only support running on Ubuntu LTS releases. If you want to give Ubuntu 21.10 a try, here is some debugging instructions that may help:
https://www.emgu.com/wiki/index.php/Download_And_Installation#System.DllNotFoundException

"libopencv_videoio_ffmpeg454_64.so" is an optional dependency, it is not the root cause of the problem. Emgu CV can run without the "libopencv_videoio_ffmpeg454_64.so" file.

**Comment by gsargent70** [comment]
After many hours I have found the solution.  It appears that if you do not have libdl named exactly as libdl.so it can not find it when booting UVtools.  On Ubuntu 21.10 you must create a symlink from your existing libdl to one named as above.  Here is an example command to do this.

sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so

Once I did this UVtools booted right up from a fresh install.  I did not need to do any recompile of emgucv.  I hope this helps others with their issues.

**Comment by emgucv** [comment]
Closing as self-resolved. The root cause was that Ubuntu 21.10 (and later non-LTS releases) merged `libdl` into glibc and no longer ship an unversioned `libdl.so` symlink. The workaround reported by the original author is:

```bash
sudo ln -s /lib/x86_64-linux-gnu/libdl.so.2 /lib/x86_64-linux-gnu/libdl.so
```

Note that Ubuntu 21.10 is a non-LTS release that has been end-of-life since July 2022. We recommend using a supported Ubuntu LTS release (22.04 or 24.04) where this issue does not arise.
