### ISSUE TITLE
[BUG] [Linux & MacOS] [4.5.5] connectedComponentsWithStats crash the program with Segmentation fault

### ISSUE THREAD

**Issue by sn4k3** [emgucv/emgucv#691]
**Describe the bug**
connectedComponentsWithStats crash the program with Segmentation fault.
Other functions seen to run file, eg morph, rotate, flip, arithmetic funcions works well, only this seens to crash my app which it doesn't with the previous version (4.5.4)

```
Thread 43 ".NET ThreadPool" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fff22d1f640 (LWP 29732)]
0x00007fff2a82ebb6 in cv::connectedcomponents::LabelingBolelli4CParallel<int, unsigned char, cv::connectedcomponents::CCStatsOp>::operator()(cv::Mat const&, cv::Mat&, int, cv::connectedcomponents::CCStatsOp&) () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
(gdb) bt
#0  0x00007fff2a82ebb6 in cv::connectedcomponents::LabelingBolelli4CParallel<int, unsigned char, cv::connectedcomponents::CCStatsOp>::operator()(cv::Mat const&, cv::Mat&, int, cv::connectedcomponents::CCStatsOp&) () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#1  0x00007fff2a82f695 in int cv::connectedComponents_sub1<cv::connectedcomponents::CCStatsOp>(cv::Mat const&, cv::Mat&, int, int, cv::connectedcomponents::CCStatsOp&) ()
   from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#2  0x00007fff2a82f9ad in cv::connectedComponentsWithStats(cv::_InputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, cv::_OutputArray const&, int, int, int) ()
   from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcvextern.so
#3  0x00007fff8229b539 in ?? ()
#4  0xffffffffffffffff in ?? ()
#5  0x000000000677e34c in ?? ()
#6  0x00007ffff74b9848 in ?? () from /home/kyra/bin/UVtools_linux-x64_v2.27.7/libcoreclr.so
#7  0x00007fff22d1ebe0 in ?? ()
#8  0x00007fff800bcda0 in ?? ()
#9  0x00007fff800bcda0 in ?? ()
#10 0x00007fff22d1e0c0 in ?? ()
#11 0x00007fff8229b539 in ?? ()
#12 0x00007fff22d1e150 in ?? ()
#13 0x00007fff10003400 in ?? ()
#14 0x00007fff800bcda0 in ?? ()
#15 0x00007fff08008aa0 in ?? ()
#16 0x0000000400000004 in ?? ()
#17 0x00007fff4bcfd588 in ?? ()
#18 0x0000000000000654 in ?? ()
#19 0x00007fff1000e900 in ?? ()
#20 0x00000000000001f8 in ?? ()
#21 0x00007fff499b5200 in ?? ()
#22 0x00007fff22d1e1e0 in ?? ()
#23 0x00007fff8229b242 in ?? ()
#24 0x00000000ffffffff in ?? ()
#25 0x00007fff22d1e160 in ?? ()
#26 0x00007fff100016b0 in ?? ()
#27 0x00007fff10003400 in ?? ()
#28 0x00007fff10003480 in ?? ()
#29 0x00007fff100016f0 in ?? ()
#30 0x000000004bdc7280 in ?? ()
#31 0x00007fff4bdc7388 in ?? ()
#32 0x00007fff4bdc7360 in ?? ()
#33 0x00007fff4bdc7338 in ?? ()
#34 0x00007fff4bdc7310 in ?? ()
#35 0x0000000400000004 in ?? ()
#36 0x00007fff4bdc72e0 in ?? ()
#37 0x00007fff4bdc72b0 in ?? ()
#38 0x00007fff4bdc7280 in ?? ()
#39 0x00007fff4bdc71d8 in ?? ()
#40 0x00007fff22d1e600 in ?? ()
#41 0x00007fff82298813 in ?? ()
#42 0x00000000ffffffff in ?? ()
#43 0x0000000000000002 in ?? ()
#44 0x00007fff8203b788 in ?? ()
#45 0x00007fff82297a90 in ?? ()
#46 0x00007fff22d1e1f0 in ?? ()
#47 0x00007fff8203b788 in ?? ()
#48 0x0000000000000000 in ?? ()
```

https://github.com/sn4k3/UVtools/blob/d9ebd966835acc61fb021846221add26de552799/UVtools.Core/Managers/IssueManager.cs#L366

**OS / Platform**
Problem happens on Linux (Ubuntu 20.04 and Fedora 35)
Windows runs fine

**.Net version**
NET 5.0

**CPU Architecture**
x86_64

**Emgu CV package used**
https://www.nuget.org/packages/Emgu.CV.runtime.ubuntu.20.04-x64/4.5.5.4823

**Comment by sn4k3** [comment]
Confirmed to be a problem in OpenCV: https://github.com/opencv/opencv/issues/21366
Not related to EmguCV

**Comment by emgucv** [comment]
Thanks for the update.

**Comment by emgucv** [comment]
Closing ticket now
