### ISSUE TITLE
[BUG] DLL loading incompatible with Windows 7

### ISSUE THREAD

**Issue by terman110** [emgucv/emgucv#702]
The LoadPackagedLibrary() function is used under Windows if LoadLibraryEx() fails. This might be the case if DLLs are missing. That can often be the case with lean binary distributions.
The problem is, that the LoadPackagedLibrary() function was introduced in Windows 8 (Version 6.2). Therefore under Windows 7 CvInvoke will throw System.EntryPointNotFoundException.

** Possible Fix **
To assure backward compatibility with Windows 7 (Version 6.1) the function must not be called for OS versions less than 6.2.
This can be achieved with `Environment.OSVersion.Version >= new Version(6, 2)`.

** OS / Platform **
Windows 7

** Exception **
```
System.Exception: Threshold Filter failed: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.TypeInitializationException: The type initializer for 'Emgu.CV.CvInvoke' threw an exception. ---> System.EntryPointNotFoundException: Unable to find an entry point named 'LoadPackagedLibrary' in DLL 'Kernel32.dll'.
   at Emgu.Util.Toolbox.LoadPackagedLibrary(String fileName, Int32 dwFlags)
   at Emgu.Util.Toolbox.LoadLibraryWindows(String dllname)
   at Emgu.Util.Toolbox.LoadLibrary(String dllname)
   at Emgu.CV.CvInvoke.LoadUnmanagedModules(String loadDirectory, String[] unmanagedModules)
   at Emgu.CV.CvInvoke.DefaultLoadUnmanagedModules(String[] modules)
   at Emgu.CV.CvInvoke..cctor()
   --- End of inner exception stack trace ---
   at Emgu.CV.CvInvoke.cvCreateImageHeader(Size size, IplDepth depth, Int32 channels)
```

**Comment by terman110** [comment]
Pull Request: #703

**Comment by emgucv** [comment]
Pull request has been merged. It will be included in the next release.
