### ISSUE TITLE
System.Exception at Emgu.CV.Capture.Run

### ISSUE THREAD

**Issue by linchuanhai** [emgucv/emgucv#73]
I don't know why? Sometimes will throw an exception, and I can not use try...catch to catch this excepiton in my codes . then my program will be stop. and the OS  will record this record:

Framework Version: v4.0.30319
Description: The process was terminated due to an unhandled exception.
Exception Info: System.Exception
Stack:
   at Emgu.CV.Capture.Run()
   at Emgu.CV.Capture.<Start>b__0(System.Object)
   at System.Threading.QueueUserWorkItemCallback.WaitCallback_Context(System.Object)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading._ThreadPoolWaitCallback.PerformWaitCallback()

**Comment by emgucv** [comment]
The `Emgu.CV.Capture` class referenced here has been replaced by `VideoCapture`. In `VideoCapture`, the internal grab loop (the equivalent of `Run()`) catches exceptions and sets `_grabState` to `Stopping` so the thread exits cleanly rather than letting an unhandled exception terminate the process. Closing now.
