### ISSUE TITLE
AccessViolationException in Concatanating Descriptors

### ISSUE THREAD

**Issue by BilalHasanKhan** [emgucv/emgucv#75]
at ScrapperConsole.BuildIndex.DescriptorManager.ConcatDescriptors(IEnumerable`1 descriptors)
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Emgu.CV.CvInvoke.cveVConcat(IntPtr src1, IntPtr src2, IntPtr dst)
   at Emgu.CV.CvInvoke.VConcat(IInputArray src1, IInputArray src2, IOutputArray dst)
   at ScrapperConsole.BuildIndex.DescriptorManager.ConcatDescriptors(IEnumerable`1 descriptors)

Code where it happens is

```
  public static Mat ConcatDescriptors(IEnumerable<Mat> descriptors)
        {
            var mat = descriptors.FirstOrDefault();
            if (mat == null) return null;
            descriptors = descriptors.Skip(1);
            Console.WriteLine("Concating Descriptors started");
            foreach (var descriptor in descriptors)
            {
                try
                {
                    var next = new Mat();
                    CvInvoke.VConcat(mat, descriptor, next);

                    next.ConvertTo(mat, DepthType.Cv8U);
        
                }
                catch(Exception ex)
                {
                    Console.Write(ex);
                    continue;
                }
            }

         
            mat.ConvertTo(mat, DepthType.Cv8U);
        
            return mat;
        }
```

**Comment by emgucv** [comment]
The `AccessViolationException` is caused by a memory corruption in the loop:

1. `mat` is a reference to the **first** element of `descriptors` (the original Mat object).
2. `next.ConvertTo(mat, DepthType.Cv8U)` writes back into `mat`, overwriting the original descriptor's native memory in place.
3. On the next iteration, `VConcat(mat, descriptor, next)` operates on corrupted data → crash.

Additionally, `new Mat()` is created inside the loop but never disposed, leaking native memory.

The correct approach is to use the `VConcat(Mat[], IOutputArray)` overload which concatenates all mats in a single call:

```csharp
public static Mat ConcatDescriptors(IEnumerable<Mat> descriptors)
{
    Mat[] list = descriptors.ToArray();
    if (list.Length == 0) return null;
    Mat result = new Mat();
    CvInvoke.VConcat(list, result);
    return result;
}
```

Closing now.
