### ISSUE TITLE
PanAndZoomPictureBox: Exceptions unhandled in OnMousewheel

### ISSUE THREAD

**Issue by brendangawn** [emgucv/emgucv#89]
*Using EmguCV from NuGet, 3.3.0.2824*

Anything that throws inside  Emgu.CV.UI.PanAndZoomPictureBox.OnMouseWheel will be unhandled and crash the app.  In this instance  SetZoomScale  trys to get image width/height while the "object is currently in use elsewhere".

***Please put a try/catch block inside OnMouseWheel so it doesn't ever crash.***

This probably applies to other event handlers in the PanAndZoomPictureBox and ImageBox classes
    
    System.InvalidOperationException: Object is currently in use elsewhere.
    
    - at System.Drawing.Image.get_Width()
    - at System.Drawing.Image.get_Size()
    - at Emgu.CV.UI.PanAndZoomPictureBox.SetZoomScale(Double zoomScale, Point fixPoint)
    - at Emgu.CV.UI.PanAndZoomPictureBox.OnMouseWheel(Object sender, MouseEventArgs e)
    - at System.Windows.Forms.Control.OnMouseWheel(MouseEventArgs e)
    - at System.Windows.Forms.Control.WmMouseWheel(Message& m)
    - at System.Windows.Forms.Control.WndProc(Message& m)
    - at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
    - at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
    - at System.Windows.Forms.NativeWindow.DebuggableCallback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
    - at System.Windows.Forms.UnsafeNativeMethods.DispatchMessageW(MSG& msg)
    - at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
    - at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
    - at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
    - at System.Windows.Forms.Application.Run(Form mainForm)
    - at JdsuTc.Program.Main() in Program.cs:line 55

**Comment by emgucv** [comment]
The `"Object is currently in use elsewhere"` exception from `Image.get_Width()` is a GDI+ thread-safety error: the bitmap is being accessed from a background thread (e.g. a capture loop setting `pictureBox.Image = newBitmap`) at the same moment the UI thread's mouse-wheel handler tries to read its size.

A `try/catch` in `OnMouseWheel` would prevent the app crash but would hide the root cause. The real fix is to ensure the image is only replaced on the UI thread:

```csharp
// From a background thread:
pictureBox.BeginInvoke((Action)(() => pictureBox.Image = newBitmap));
```

Or, if you reuse a single bitmap and draw into it from the background thread, wrap both the draw and the UI reads in a `lock`. Closing now.
