### ISSUE TITLE
Attempting to JIT compile method "(wrapper native-to-managed) int Emgu.CV.CvInvoke:CvErrorHandler (int,intptr,intptr,intptr,int,intptr)" while running in aot-only mode.

### ISSUE THREAD

**Issue by hirendh** [emgucv/emgucv#926]
We have created cross platform application in .Net MAUI with .Net 8 Latest Version. In app we have used **Emgu.CV.runtime.maui.macos.4.8.1.5350.nupkg** nuget package. when we use any operation related CvInvoke it's throw exception. Following is code in i got this exception.

Convert SKbitmap to Mat  :
             
   ```
 Mat source = new Mat();
    byte[] bytes;
    using (SKImage img = SKImage.FromBitmap(skBitmap))
    using (SKData data = img.Encode())
    {
                bytes = data.ToArray();
    }
    CvInvoke.Imdecode(bytes, ImreadModes.Unchanged, source);
     int channels = skBitmap.BytesPerPixel;
    source = new Mat(new System.Drawing.Size(skBitmap.Width, skBitmap.Height), DepthType.Cv8U, channels, 
   skBitmap.GetPixels(), skBitmap.RowBytes);
```

throw Exception: 

```
System.TypeInitializationException: TypeInitialization_Type, Emgu.CV.MatInvoke
 ---> System.TypeInitializationException: TypeInitialization_Type, Emgu.CV.CvInvoke
 ---> System.ExecutionEngineException: Attempting to JIT compile method '(wrapper native-to-managed) int Emgu.CV.CvInvoke:CvErrorHandler (int,intptr,intptr,intptr,int,intptr)' while running in aot-only mode. See https://docs.microsoft.com/xamarin/ios/internals/limitations for more information.
at Emgu.CV.CvInvoke..cctor()
   Exception_EndOfInnerExceptionStack
   at Emgu.CV.MatInvoke..cctor()
   Exception_EndOfInnerExceptionStack
   at Emgu.CV.Mat..ctor()

```
**OS / Platform**
Mac OS  Sonoma 14.3.1

**.Net version**
.Net 8 

**CPU Architecture**
ARM64

**Emgu CV package used**
Emgu.CV (4.8.1.5350)
Emgu.CV.Bitmap (4.8.1.5350)
Emgu.CV.runtime.maui.macos (4.8.1.5350)

This problem is occur in only Mac Platform (net8.0-maccatalyst with arm64).

**Expected behavior**
Emgu.CV.CvInvoke method work without any exception.

**Comment by hirendh** [comment]
This issue resolved now if any one felt this issue please add below code in csproj file 

<PropertyGroup Condition="'$(RuntimeIdentifier)' == 'maccatalyst-arm64' and '$(Configuration)' == 'Release'">
		<MtouchInterpreter>-all,Emgu.CV</MtouchInterpreter>
		<MtouchInterpreter>-all,Emgu.CV.Bitmap</MtouchInterpreter>
	</PropertyGroup>

**Comment by emgucv** [comment]
Thanks for pointing that out. 

This commit fix the problem too:
bbeb004d56fad66a967a5d056f822ddeeb913120

It will be included in the next release. You won't need to add the above project settings once the next release is out.

**Comment by mfsigauravk** [comment]
Hi, I am using pro (paid) version of Emgu.CV runtime packages currently using this 
Emgu.CV.runtime.maui.macos.4.8.1.5350 for MAUI Mac
Emgu.CV.runtime.windows.dldt.4.8.1.5350- for MAUI windows

Now i am updating the packages and I have new version for windows (Emgu.CV.runtime.windows.dldt.4.9.0.5494)
but there is no update (4.9 version) for Mac

**Comment by emgucv** [comment]
Closing as completed — the AOT crash was fixed in bbeb004d56fad66a967a5d056f822ddeeb913120 (the native-to-managed error callback is now decorated with `[AOT.MonoPInvokeCallback]`, so it is AOT-compiled instead of requiring the JIT), and the fix has shipped in every release since 4.10: the `MtouchInterpreter` workaround from the first comment is no longer needed on current packages. @mfsigauravk — your question is about commercial package availability rather than this bug; please reach out through the commercial support channel (support@emgu.com) for the MAUI macOS package release schedule.
